### ISSUE TITLE
Entire app exits when using @BackButton with onBackButton()

### ISSUE THREAD

**Issue by will0684** [ScaffoldDigital/ionic-hardware-buttons#1]
Hi guys, first off, thank you to the contributor(s) who made this awesome little improvement to the less than ideal Ionic built-in. Here is what I am trying to do:

I have a Help Modal that can be opened on every page for which I want to override the back button so that it dismisses the modal. This is because in Ionic v3 pressing the back button with a modal open navigates the navigation stack behind the modal out of sight of the user. In my attempt to implement onBackButton, I found that the entire app now closes on hitting the back button while the Help Modal is open. This behaviour is different from Ionic default but I don't understand why it is occurring. Here is my Help Modal:

```
import { Component } from "@angular/core";
import { TranslateService } from "@ngx-translate/core";
import {
  ViewController,
  IonicPage,
  NavController,
  NavParams,
  IonicApp,
  MenuController,
  Keyboard
} from "ionic-angular";
import { Logger } from "winston";
import { LogProvider } from "@providers";
import { BackButton } from "@scaffold-digital/ionic-hardware-buttons";

@IonicPage()
@Component({
  selector: "page-help-modal",
  templateUrl: "help-modal.html"
})
export class HelpModalPage {
  public modalTitle: string;
  public helpSections: any;
  private readonly logger: Logger;

  @BackButton()
  public onBackButton() {
    this.dismiss();
    return false;
  }

  constructor(
    public viewCtrl: ViewController,
    public navCtrl: NavController,
    public keyboard: Keyboard,
    public navParams: NavParams,
    public translate: TranslateService,
    private readonly logProvider: LogProvider,
    public ionicApp: IonicApp,
    public menuCtrl: MenuController
  ) {
    this.logger = this.logProvider.getLogger();
    this.modalTitle = navParams.get("modalTitle");
    this.logger.info(this.modalTitle);
    this.helpSections = navParams.get("sections");
    this.logger.info(this.helpSections);
  }

  ionViewDidLoad() {
    this.logger.info("ionViewDidLoad HelpModalPage");
  }

  dismiss() {
    this.viewCtrl
      .dismiss()
      .then(() => this.logger.info("Help modal dismissed"))
      .catch((reason: any) => this.logger.error(reason));
  }
}
```

The modal is created with a modalCtrl.create(HelpModal) call.

app.module.ts includes HardwareButtons in it's providers and hardwareButtons.init() is in the constructor of app.component.ts.

You can also view the entire project here: 

https://github.com/MTS-STM/MTSApp/tree/ionic-hardware-buttons

Thank you

**Comment by rabamus** [comment]
Hey Jordan,

Honestly, I don't believe we've ever used it with a modal before so I suspect it simply doesn't work. Essentially it runs through each active NavController to see if the @BackButton decorator was applied to the active view and if so it triggers it. My guess right now is that the modal isn't part of that stack and the underlying page is probably the root page of the stack?

That said, I'd imagine it should be possible to make it work with modals. I'll take a look and get back to you.

Cheers,
Rob

**Comment by will0684** [comment]
Thank you for such a prompt and clear reply. Yes I believe you are correct in your assumption. I love the simplicity of the syntax and would love to use it all over as opposed to the Ionic default. I'll take a look at the source and see if I can make any contributions myself as well. Once again, thank you!

**Comment by rabamus** [comment]
Hi @will0684,

Sorry for the delay in getting this resolved. I've just committed a change that should mean this works on any active view (modal or otherwise). Planning to release an update that includes that fix shortly.

Cheers,
Rob
